swagger: "2.0"
info:
  version: "0.0.1"
  title: IKEA backend API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /doLogin:
    # binds a127 app logic to a route
    x-swagger-router-controller: users_ctrl
    post:
      description: Authenticates users
      operationId: doLogin
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        "201":
          description: Login succeeded
          headers:
            Set-Cookie:
              type: string
              default: "auth-cookie=someRandomValueHere"
              description: Authentication cookie is returned
        "401":
          description: Login failed
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: internal server error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
# Let's keep this in alphabetical order
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  LoginRequest:
    required: [email, password]
    properties:
      email:
        type: string
      password:
        type: string
